version: "3.7"
services:
  postgres:
    image: postgres:15.1-alpine
    container_name: postgres
    env_file: .env
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PORT: ${DB_PORT}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    mem_limit: 1G

  rails:
    build:
      context: ./src
      dockerfile: ruby.dockerfile
    container_name: rails
    env_file: .env
    environment:
      RAILS_ENV: ${RAILS_ENV}
    volumes:
      - ./src:/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  postgres_data:
