source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.0'

gem 'activeadmin', '~> 2.13', '>= 2.13.1'
gem 'bcrypt', '~> 3.1', '>= 3.1.18'
gem 'bootsnap', '~> 1.16', require: false
gem 'devise', '~> 4.8', '>= 4.8.1'
gem 'draper', '~> 4.0', '>= 4.0.2'
# gem 'image_processing', '~> 1.2'
# gem 'jbuilder'
gem 'jsonapi-serializers', '~> 1.0', '>= 1.0.1'
# gem 'kredis'
gem 'pg', '~> 1.1'
gem 'rails', '~> 7.0.4', '>= 7.0.4.2'
gem 'rails-i18n', '~> 7.0', '>= 7.0.6'
# gem 'rack-cors'
# gem 'redis', '~> 4.0'
gem 'sass-rails', '~> 6.0'
gem 'sprockets', '< 4'
gem 'tzinfo-data', platforms: %i[ mingw mswin x64_mingw jruby ]

group :development, :test do
  gem 'debug', platforms: %i[ mri mingw x64_mingw ]
  gem 'foreman', '~> 0.87.2'
  gem 'puma', '~> 5.0'
end

group :development do
#  gem 'spring'
end
